export const fontFamily = {
  MontserratBlack: "MontserratBlack",
  MontserratBlackItalic: "MontserratBlackItalic",
  MontserratBold: "MontserratBold",
  MontserratBoldItalic: "MontserratBoldItalic",
  MontserratExtraBold: "MontserratExtraBold",
  MontserratExtraBoldItalic: "MontserratExtraBoldItalic",
  MontserratExtraLight: "MontserratExtraLight",
  MontserratExtraLightItalic: "MontserratExtraLightItalic",
  MontserratItalic: "MontserratItalic",
  MontserratLight: "MontserratLight",
  MontserratLightItalic: "MontserratLightItalic",
  MontserratMedium: "MontserratMedium",
  MontserratMediumItalic: "MontserratMediumItalic",
  MontserratRegular: "MontserratRegular",
  MontserratSemiBold: "MontserratSemiBold",
  MontserratSemiBoldItalic: "MontserratSemiBoldItalic",
  MontserratThin: "MontserratThin",
  MontserratThinItalic: "MontserratThinItalic",
};
